In [2]:
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

In [4]:
data = pd.read_csv('cleaned_data.csv')

In [5]:
log_reg = LogisticRegression()

In [17]:
x = np.array(data.drop("depression", axis=1))
len(x)

36259

In [18]:
y = data["depression"]
len(y)

36259

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [34]:
len(x_train)

25381

In [35]:
len(x_test)

10878

In [36]:
len(y_train)

25381

In [37]:
len(y_test)

10878

In [38]:
log_reg.fit(x_train, y_train)

LogisticRegression()

In [39]:
print(log_reg.coef_)
print(log_reg.intercept_)
# input = [[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]
y_pred = log_reg.predict(x_test)
y_pred

[[-0.46062249 -0.00719172  0.73556196  0.53758902  0.30273901  0.42411969
   0.34855603  0.47997796  0.22578665  0.42268377 -0.67604978  1.21910026
   0.36616392  0.68622374 -0.06886727 -0.18214756  0.35389952  0.39106806]]
[-4.13433463]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
y_test
# confusion_matrix(y_test, y_pred)

5822     0
29300    0
12131    0
2055     1
10545    0
        ..
32522    0
13426    0
5670     0
24017    0
34303    0
Name: depression, Length: 10878, dtype: int64

In [41]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
confusion_matrix(y_test, y_pred)
# y_pred.shape

array([[9917,   59],
       [ 840,   62]], dtype=int64)

In [43]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.92      0.99      0.96      9976\n           1       0.51      0.07      0.12       902\n\n    accuracy                           0.92     10878\n   macro avg       0.72      0.53      0.54     10878\nweighted avg       0.89      0.92      0.89     10878\n'